(()=>{
 if(location.hostname!=='ometv.chat'&&location.hostname!=='127.0.0.1')return;
 if(location.hostname==='ometv.chat'&&location.pathname!=='/embed/index.html')return;
 if(window.__videoHost||!navigator.mediaDevices||!window.MediaRecorder||!window.MediaSource)return;
 const NativeRTC=window.RTCPeerConnection;const width=window.__videoHostConfig?.width===320?320:640,height=width*9/16,fps=width===320?10:15;
 const audio=new AudioContext(),outAudio=audio.createMediaStreamDestination(),remoteAudio=audio.createMediaStreamDestination();
 const outgoing=document.createElement('canvas'),preview=document.createElement('canvas');for(const c of [outgoing,preview]){c.width=width;c.height=height;}
 const outCtx=outgoing.getContext('2d'),previewCtx=preview.getContext('2d');
 const outVideo=outgoing.captureStream(fps),previewVideo=preview.captureStream(fps);
 const virtual=new MediaStream([...outVideo.getVideoTracks(),...outAudio.stream.getAudioTracks()]);
 const previewStream=new MediaStream([...previewVideo.getVideoTracks(),...remoteAudio.stream.getAudioTracks()]);
 const incoming=document.createElement('video');incoming.autoplay=true;incoming.playsInline=true;incoming.muted=false;incoming.volume=1;incoming.style.cssText='position:fixed;left:-10000px;width:1px;height:1px';
 const player=new VideoStreamPlayer(incoming),incomingSource=audio.createMediaElementSource(incoming),gain=audio.createGain();gain.gain.value=0;incomingSource.connect(gain).connect(outAudio);const meter=audio.createAnalyser();meter.fftSize=2048;gain.connect(meter);
 let previewRequested=false,enabled=false,otherConnected=false,remote=null,remoteSource=null,recorder=null,generation=0,documentId=crypto.randomUUID(),recordTimer=null,remoteWasConnected=false,ended=false,disposed=false,fixture=null,cameraCalls=0;
 const peers=new Set();
 const mount=()=>{if(document.body&&!incoming.isConnected)document.body.append(incoming);};document.addEventListener('DOMContentLoaded',mount);mount();
 navigator.mediaDevices.getUserMedia=async constraints=>{cameraCalls++;if(disposed)throw new DOMException('Session closed','AbortError');await audio.resume();const tracks=[];if(constraints.video)tracks.push(...virtual.getVideoTracks().map(t=>t.clone()));if(constraints.audio)tracks.push(...virtual.getAudioTracks().map(t=>t.clone()));if(!tracks.length)throw new TypeError('Audio or video is required');return new MediaStream(tracks);};
 function peerLive(p){return p.connectionState==='connected'||['connected','completed'].includes(p.iceConnectionState);}
 function connected(){const view=document.getElementById('remote-video');return !ended&&!!remote&&remote.getTracks().some(t=>t.readyState==='live')&&([...peers].some(peerLive)||!!fixture||(!peers.size&&view?.srcObject===remote&&view.readyState>=2&&!view.paused));}
 function stopRecording(){clearTimeout(recordTimer);if(recorder?.state==='recording')recorder.stop();recorder=null;}
 function startRecording(){stopRecording();if(!connected()||disposed||!fixture&&!previewRequested&&!(enabled&&otherConnected))return;const id=documentId+':'+(++generation);const r=recorder=new MediaRecorder(previewStream,{mimeType:'video/webm;codecs=vp8,opus',videoBitsPerSecond:width===320?200000:600000,audioBitsPerSecond:64000});let chain=Promise.resolve();r.ondataavailable=e=>{if(!e.data.size)return;chain=chain.then(async()=>{const bytes=new Uint8Array(await e.data.arrayBuffer());let text='';for(let i=0;i<bytes.length;i++)text+=String.fromCharCode(bytes[i]);if(!disposed)await window.__videoSegment?.({generation:id,data:btoa(text)});}).catch(()=>{});};r.start(250);recordTimer=setTimeout(startRecording,25000);}
 function setRemote(stream){if(remote===stream&&(!stream?.getAudioTracks().length||remoteSource))return;if(remoteSource){remoteSource.disconnect();remoteSource=null;}remote=stream;if(stream?.getAudioTracks().length){remoteSource=audio.createMediaStreamSource(stream);remoteSource.connect(remoteAudio);}if(stream)startRecording();else stopRecording();}
 if(NativeRTC){const WrappedRTC=class extends NativeRTC{constructor(...args){super(...args);peers.add(this);this.addEventListener('track',e=>{ended=false;if(e.streams?.[0])setRemote(e.streams[0]);else if(e.track){const stream=remote||new MediaStream();if(!stream.getTracks().includes(e.track))stream.addTrack(e.track);setRemote(stream);}});const changed=()=>{if(peerLive(this)&&!recorder)startRecording();if(['closed','failed','disconnected'].includes(this.connectionState)||['closed','failed','disconnected'].includes(this.iceConnectionState)){if(![...peers].some(peerLive)){if(remoteWasConnected)ended=true;setRemote(null);gain.gain.value=0;}}};this.addEventListener('connectionstatechange',changed);this.addEventListener('iceconnectionstatechange',changed);}};window.RTCPeerConnection=WrappedRTC;if(window.webkitRTCPeerConnection===NativeRTC)window.webkitRTCPeerConnection=WrappedRTC;}
 function draw(ctx,video,label){ctx.fillStyle='#07150e';ctx.fillRect(0,0,width,height);if(video?.readyState>=2){ctx.drawImage(video,0,0,width,height);}else{ctx.fillStyle='#70eba4';ctx.font=(width===320?'14':'22')+'px sans-serif';ctx.textAlign='center';ctx.fillText(label,width/2,height/2);}}
 const remoteView=document.createElement('video');remoteView.autoplay=true;remoteView.muted=true;remoteView.playsInline=true;
 const renderTimer=setInterval(()=>{mount();if(fixture){const ctx=fixture.canvas.getContext('2d');ctx.fillStyle=fixture.color;ctx.fillRect(0,0,640,360);}const siteVideo=document.getElementById('remote-video');if(!fixture&&siteVideo?.srcObject&&siteVideo.srcObject!==remote)setRemote(siteVideo.srcObject);const needPreview=!!fixture||previewRequested||(enabled&&otherConnected),nativePreview=siteVideo?.srcObject===remote&&siteVideo.readyState>=2;const fallback=needPreview&&!nativePreview?remote:null;if(remoteView.srcObject!==fallback){remoteView.srcObject=fallback;if(fallback)remoteView.play().catch(()=>{});}const live=connected();if(live)remoteWasConnected=true;gain.gain.value=enabled&&otherConnected&&live?1:0;if(needPreview)draw(previewCtx,live?(nativePreview?siteVideo:remoteView):null,'Waiting for participant');draw(outCtx,enabled&&otherConnected&&live?incoming:null,'Consensual video bridge · waiting');},1000/fps);
 window.__videoHost={
  status(){
   const visible=el=>{if(el.closest('[hidden],[aria-hidden="true"],[inert]'))return false;if(el.checkVisibility&&!el.checkVisibility({checkOpacity:true,checkVisibilityCSS:true}))return false;const rect=el.getBoundingClientRect();if(!rect.width||!rect.height||rect.bottom<=0||rect.right<=0||rect.top>=innerHeight||rect.left>=innerWidth)return false;for(let node=el;node instanceof Element;node=node.parentElement){const style=getComputedStyle(node);if(style.display==='none'||style.visibility==='hidden'||Number(style.opacity)===0)return false;}return true;};
   const labels=[...document.querySelectorAll('[data-tr]')].filter(visible),texts=labels.map(el=>(el.innerText||'').replace(/\s+/g,' ').trim());
   const restricted=labels.some(el=>el.dataset.tr==='youre-banned')||texts.some(text=>/^(?:you (?:are|have been) banned|your (?:account|access|session|ip(?: address)?) (?:is|has been) (?:banned|blocked|restricted)|access (?:is |has been )?denied|ban expires(?: in|:))/i.test(text));
   const cameraError=texts.some(text=>/^(?:camera (?:was |is )?(?:not found|denied|unavailable)|(?:cannot|could not|unable to) access (?:your |the )?camera|camera access (?:was |is )?denied)/i.test(text));
   const networkError=texts.some(text=>/^(?:connection failed|server (?:is )?unavailable|network error)(?:[.!:]|$)/i.test(text));
   const duplicateSession=/you have opened the application in another window or in another browser/i.test(document.body?.innerText||'');
   const nativeError=duplicateSession?'OmeTV requires a separate active session for each side. This session was closed because it is open in another window or browser.':restricted?'OmeTV has restricted this session.':cameraError?'OmeTV could not access the hosted camera.':networkError?'OmeTV could not connect to its server.':'';
   const controls=['start','stop'].map(key=>{const label=document.querySelector('[data-tr="'+key+'"]'),button=label?.closest('.btn');return {key,present:!!button,classes:button?.className||'',ariaDisabled:button?.getAttribute('aria-disabled'),visible:!!button&&visible(button)};});const local=document.getElementById('local-video');
   return {cameraCalls,controls,localVideo:{ready:local?.readyState||0,paused:local?.paused??true,tracks:local?.srcObject?.getTracks?.().map(t=>({kind:t.kind,state:t.readyState}))||[]},topLevel:window===window.top,nativeSessionMode:!!window.config?.sn,connected:connected(),ended,searching:labels.some(el=>/^(searching|search|looking|connecting)(_|$)/i.test(el.dataset.tr)),nativeError,login:/Become an OmeTV member|Continue with.*Google/.test(document.body?.innerText||''),verification:/verify (?:that )?you are human|checking your browser|unusual traffic/i.test(document.body?.innerText||''),mediaReady:!disposed,audioState:audio.state,streamGeneration:generation,receiverFailed:player.failed,bridgeEnabled:enabled&&otherConnected,noticeKeys:labels.map(el=>el.dataset.tr).filter(key=>/ban|error|camera|search|connect|verif/i.test(key)).map(key=>key.replace(/[^a-z0-9_-]/gi,'').slice(0,80)).slice(0,30),peerStates:[...peers].map(p=>({connection:p.connectionState,ice:p.iceConnectionState})),remoteTracks:remote?.getTracks().map(t=>({kind:t.kind,state:t.readyState}))||[]};
  },
  routing(value){enabled=!!value.enabled;otherConnected=!!value.otherConnected;previewRequested=!!value.preview;if(!enabled||!otherConnected)gain.gain.value=0;if(fixture||previewRequested||(enabled&&otherConnected)){if(!recorder)startRecording();}else stopRecording();},
  receive(segment){player.push(segment);audio.resume().catch(()=>{});},
  clearIncoming(){player.dispose();otherConnected=false;gain.gain.value=0;},
  restart(){startRecording();},
  async send(text){const input=document.getElementById('chat-text');if(!connected()||!input||input.disabled)return false;const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(input,text);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));return true;},
  async fixture(color,frequency){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,640,360);const tone=audio.createOscillator(),dest=audio.createMediaStreamDestination();tone.frequency.value=frequency;tone.connect(dest);tone.start();fixture={canvas,tone,dest,color};await audio.resume();const stream=new MediaStream([...canvas.captureStream(15).getTracks(),...dest.stream.getTracks()]);setRemote(stream);startRecording();return true;},
  diagnostics(){const bins=new Uint8Array(meter.frequencyBinCount);meter.getByteFrequencyData(bins);let peak=0;for(let i=3;i<150;i++)if(bins[i]>bins[peak])peak=i;return {audioPeak:bins[peak]>20?peak*audio.sampleRate/meter.fftSize:0,outgoingPixel:Array.from(outCtx.getImageData(width/2,height*100/360,1,1).data),incomingReady:incoming.readyState,incomingTime:incoming.currentTime,buffered:player.buffer?.buffered.length||0,receiverFailed:player.failed,...this.status()};},
  dispose(){disposed=true;clearInterval(renderTimer);stopRecording();player.dispose();for(const t of virtual.getTracks())t.stop();for(const t of previewStream.getTracks())t.stop();fixture?.tone.stop();audio.close();}
 };
})();
