(()=>{
 if(location.hostname!=='ometv.chat'&&location.hostname!=='127.0.0.1')return;
 if(window.__videoHost||!navigator.mediaDevices||!window.MediaRecorder||!window.MediaSource)return;
 const NativeRTC=window.RTCPeerConnection;
 const audio=new AudioContext(),outAudio=audio.createMediaStreamDestination(),remoteAudio=audio.createMediaStreamDestination();
 const outgoing=document.createElement('canvas'),preview=document.createElement('canvas');for(const c of [outgoing,preview]){c.width=640;c.height=360;}
 const outCtx=outgoing.getContext('2d'),previewCtx=preview.getContext('2d');
 const outVideo=outgoing.captureStream(15),previewVideo=preview.captureStream(15);
 const virtual=new MediaStream([...outVideo.getVideoTracks(),...outAudio.stream.getAudioTracks()]);
 const previewStream=new MediaStream([...previewVideo.getVideoTracks(),...remoteAudio.stream.getAudioTracks()]);
 const incoming=document.createElement('video');incoming.autoplay=true;incoming.playsInline=true;incoming.muted=false;incoming.volume=1;incoming.style.cssText='position:fixed;left:-10000px;width:1px;height:1px';
 const player=new VideoStreamPlayer(incoming),incomingSource=audio.createMediaElementSource(incoming),gain=audio.createGain();gain.gain.value=0;incomingSource.connect(gain).connect(outAudio);const meter=audio.createAnalyser();meter.fftSize=2048;gain.connect(meter);
 let enabled=false,otherConnected=false,remote=null,remoteSource=null,recorder=null,generation=0,documentId=crypto.randomUUID(),recordTimer=null,remoteWasConnected=false,ended=false,disposed=false,fixture=null;
 const peers=new Set();
 const mount=()=>{if(document.body&&!incoming.isConnected)document.body.append(incoming);};document.addEventListener('DOMContentLoaded',mount);mount();
 navigator.mediaDevices.getUserMedia=async constraints=>{if(disposed)throw new DOMException('Session closed','AbortError');await audio.resume();const tracks=[];if(constraints.video)tracks.push(...virtual.getVideoTracks().map(t=>t.clone()));if(constraints.audio)tracks.push(...virtual.getAudioTracks().map(t=>t.clone()));if(!tracks.length)throw new TypeError('Audio or video is required');return new MediaStream(tracks);};
 function connected(){return !!remote&&remote.getTracks().some(t=>t.readyState==='live')&&([...peers].some(p=>p.connectionState==='connected')||!!fixture);}
 function stopRecording(){clearTimeout(recordTimer);if(recorder?.state==='recording')recorder.stop();recorder=null;}
 function startRecording(){stopRecording();if(!connected()||disposed)return;const id=documentId+':'+(++generation);const r=recorder=new MediaRecorder(previewStream,{mimeType:'video/webm;codecs=vp8,opus',videoBitsPerSecond:600000,audioBitsPerSecond:64000});let chain=Promise.resolve();r.ondataavailable=e=>{if(!e.data.size)return;chain=chain.then(async()=>{const bytes=new Uint8Array(await e.data.arrayBuffer());let text='';for(let i=0;i<bytes.length;i++)text+=String.fromCharCode(bytes[i]);if(!disposed)await window.__videoSegment?.({generation:id,data:btoa(text)});}).catch(()=>{});};r.start(250);recordTimer=setTimeout(startRecording,25000);}
 function setRemote(stream){if(remote===stream)return;if(remoteSource){remoteSource.disconnect();remoteSource=null;}remote=stream;if(stream?.getAudioTracks().length){remoteSource=audio.createMediaStreamSource(stream);remoteSource.connect(remoteAudio);}if(stream)startRecording();else stopRecording();}
 if(NativeRTC)window.RTCPeerConnection=class extends NativeRTC{constructor(...args){super(...args);peers.add(this);this.addEventListener('track',e=>{if(e.streams[0])setRemote(e.streams[0]);});this.addEventListener('connectionstatechange',()=>{if(this.connectionState==='connected'&&!recorder)startRecording();if(['closed','failed','disconnected'].includes(this.connectionState)){if(![...peers].some(p=>p.connectionState==='connected')){if(remoteWasConnected)ended=true;setRemote(null);gain.gain.value=0;}}});}};
 function draw(ctx,video,label){ctx.fillStyle='#07150e';ctx.fillRect(0,0,640,360);if(video?.readyState>=2){ctx.drawImage(video,0,0,640,360);}else{ctx.fillStyle='#70eba4';ctx.font='22px sans-serif';ctx.textAlign='center';ctx.fillText(label,320,180);}}
 const remoteView=document.createElement('video');remoteView.autoplay=true;remoteView.muted=true;remoteView.playsInline=true;
 const renderTimer=setInterval(()=>{mount();if(fixture){const ctx=fixture.canvas.getContext('2d');ctx.fillStyle=fixture.color;ctx.fillRect(0,0,640,360);}const siteVideo=document.getElementById('remote-video');if(!fixture&&siteVideo?.srcObject&&siteVideo.srcObject!==remote)setRemote(siteVideo.srcObject);if(remoteView.srcObject!==remote){remoteView.srcObject=remote;remoteView.play().catch(()=>{});}const live=connected();if(live)remoteWasConnected=true;gain.gain.value=enabled&&otherConnected&&live?1:0;draw(previewCtx,live?remoteView:null,'Waiting for participant');draw(outCtx,enabled&&otherConnected&&live?incoming:null,'Consensual video bridge · waiting');},66);
 window.__videoHost={
  status(){const text=(document.body?.innerText||'').slice(0,15000);return {connected:connected(),ended,login:/Become an OmeTV member|Continue with.*Google/.test(text),verification:/verify (?:that )?you are human|checking your browser|unusual traffic/i.test(text),mediaReady:!disposed,audioState:audio.state,streamGeneration:generation,receiverFailed:player.failed,bridgeEnabled:enabled&&otherConnected,remoteTracks:remote?.getTracks().map(t=>({kind:t.kind,state:t.readyState}))||[]};},
  routing(value){enabled=!!value.enabled;otherConnected=!!value.otherConnected;if(!enabled||!otherConnected)gain.gain.value=0;},
  receive(segment){player.push(segment);audio.resume().catch(()=>{});},
  clearIncoming(){player.dispose();otherConnected=false;gain.gain.value=0;},
  restart(){startRecording();},
  async send(text){const input=document.getElementById('chat-text');if(!connected()||!input||input.disabled)return false;const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(input,text);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));return true;},
  async fixture(color,frequency){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,640,360);const tone=audio.createOscillator(),dest=audio.createMediaStreamDestination();tone.frequency.value=frequency;tone.connect(dest);tone.start();fixture={canvas,tone,dest,color};await audio.resume();const stream=new MediaStream([...canvas.captureStream(15).getTracks(),...dest.stream.getTracks()]);setRemote(stream);startRecording();return true;},
  diagnostics(){const bins=new Uint8Array(meter.frequencyBinCount);meter.getByteFrequencyData(bins);let peak=0;for(let i=3;i<150;i++)if(bins[i]>bins[peak])peak=i;return {audioPeak:bins[peak]>20?peak*audio.sampleRate/meter.fftSize:0,outgoingPixel:Array.from(outCtx.getImageData(320,100,1,1).data),incomingReady:incoming.readyState,incomingTime:incoming.currentTime,buffered:player.buffer?.buffered.length||0,receiverFailed:player.failed,...this.status()};},
  dispose(){disposed=true;clearInterval(renderTimer);stopRecording();player.dispose();for(const t of virtual.getTracks())t.stop();for(const t of previewStream.getTracks())t.stop();fixture?.tone.stop();audio.close();}
 };
})();
