export function voiceReady(){return [...document.querySelectorAll('*')].some(e=>{const s=e.__vue__?.$store?.state;if(!s?.system||!s.user)return false;return !!(s.system.isFirstLoaded||s.system.captchaRequired||s.system.hcaptchaRequired||s.system.forceDisconnectReason||s.system.errorRegistered||s.system.isAuth&&s.system.socketConnected&&s.user.tokenId!=null);});}
// Observe the voice client's normal startup. Do not change its live store or reauthorize.
export function confirmVoiceSession({token,timeout=10000}){
 const vm=[...document.querySelectorAll('*')].map(e=>e.__vue__).find(v=>v?.$store?.state?.system&&v.$store.state.user);if(!vm)return {ok:false,reason:'client-not-ready'};const store=vm.$store;
 const snapshot=()=>{let saved=false;try{saved=JSON.parse(localStorage.getItem('storage_audio_v2'))?.user?.authToken===token;}catch{}const s=store.state;return {savedTokenMatches:saved,liveTokenMatches:s.user.authToken===token,identityPresent:s.user.tokenId!=null,authenticated:s.system.isAuth===true,socketConnected:s.system.socketConnected===true,captcha:!!s.system.captchaRequired,hcaptcha:!!s.system.hcaptchaRequired,restricted:!!s.system.forceDisconnectReason,registrationError:Number(s.system.errorRegistered)||0};};
 const outcome=()=>{const d=snapshot();let reason=null,ok=false;if(d.captcha||d.hcaptcha)reason='verification-required';else if(d.restricted)reason='native-restriction';else if(d.registrationError)reason='native-registration-error-'+d.registrationError;else if(d.savedTokenMatches&&d.liveTokenMatches&&d.identityPresent&&d.authenticated&&d.socketConnected){ok=true;reason='native-session-confirmed';}else if(d.authenticated&&d.identityPresent&&(!d.liveTokenMatches||!d.savedTokenMatches))reason='token-not-accepted';return reason?{ok,reason,diagnostics:d}:null;};
 const initial=outcome();if(initial)return initial;
 return new Promise(resolve=>{let done=false,unsubscribe=()=>{},timer,poll;const finish=result=>{if(done)return;done=true;clearTimeout(timer);clearInterval(poll);unsubscribe();resolve(result);};const check=()=>{if(done)return;const result=outcome();if(result)finish(result);};
 if(typeof store.subscribe==='function')unsubscribe=store.subscribe(()=>Promise.resolve().then(check));timer=setTimeout(()=>finish({ok:false,reason:'native-authorization-timeout',diagnostics:snapshot()}),timeout);poll=setInterval(check,50);check();
 });
}
