import {test} from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {chromium} from 'playwright';import {AudioGraph} from '../audio-graph.js';
let pulse=false;try{execFileSync('pulseaudio',['--version'],{stdio:'ignore'});pulse=true;}catch{}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
test('native browser microphones receive opposite-side audio, and muting stops both directions',{skip:!pulse,timeout:60000},async()=>{
 const graph=new AudioGraph(),browsers=[];try{await graph.ensure();const pages=[];
 for(let i=0;i<2;i++){const browser=await chromium.launch({headless:true,channel:'chromium',ignoreDefaultArgs:['--mute-audio'],env:graph.browserEnv(i),args:['--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required']});browsers.push(browser);const context=await browser.newContext();await context.grantPermissions(['microphone'],{origin:'https://voice-fixture.test'});await context.route('https://voice-fixture.test/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><title>Private audio routing fixture</title>'}));const page=await context.newPage();await page.goto('https://voice-fixture.test/');await page.evaluate(async hz=>{let mic,context;try{mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});}catch(e){throw Error('Native microphone: '+e.name+' '+e.message);}try{context=new AudioContext();await context.resume();}catch(e){throw Error('Native output: '+e.name+' '+e.message);}const input=context.createMediaStreamSource(mic),analyser=context.createAnalyser();analyser.fftSize=4096;input.connect(analyser);const tone=context.createOscillator(),gain=context.createGain();tone.frequency.value=hz;gain.gain.value=.1;tone.connect(gain).connect(context.destination);tone.start();window.fixture={context,mic,analyser};window.measure=()=>{const spectrum=new Float32Array(analyser.frequencyBinCount);analyser.getFloatFrequencyData(spectrum);let peak=1;for(let n=2;n<spectrum.length;n++)if(spectrum[n]>spectrum[peak])peak=n;return {hz:peak*context.sampleRate/analyser.fftSize,db:spectrum[peak]};};},i?880:440);pages.push(page);}
 await delay(1200);for(const page of pages){const value=await page.evaluate(()=>measure());assert.ok(value.db< -60,JSON.stringify({phase:'muted',...value}));}
 await graph.routing(true);await delay(1600);const values=await Promise.all(pages.map(p=>p.evaluate(()=>measure())));assert.ok(Math.abs(values[0].hz-880)<25&&values[0].db>-50,JSON.stringify(values[0]));assert.ok(Math.abs(values[1].hz-440)<25&&values[1].db>-50,JSON.stringify(values[1]));
 await graph.routing(false);await delay(1600);for(const page of pages){const value=await page.evaluate(()=>measure());assert.ok(value.db< -60,JSON.stringify({phase:'muted-again',...value}));}
 }finally{for(const browser of browsers)await browser.close();await graph.close();}
});
