import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {EventEmitter} from 'node:events';import {AudioHost} from '../audio-host.js';import {confirmVoiceSession} from '../voice-session.js';
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'voice-test-'));const routes=[],states=[{connected:true,status:'connected'},{connected:true,status:'connected'}];const graph={process:true,routing:async v=>routes.push(v),close:async()=>{},capture:()=>{const child=new EventEmitter();child.stdout=new EventEmitter();child.kill=()=>{};return child;}};const host=new AudioHost({data:dir,graph});clearInterval(host.timer);await host.loaded;host.slots=[0,1].map(i=>({page:{evaluate:async()=>states[i]},browser:{close:async()=>{}},connected:true,epoch:String(i)}));return {host,states,routes,done:async()=>{await host.shutdown();await rm(dir,{recursive:true,force:true});}};}
test('audio routes only after consent and both sides connect; lost connection mutes',async()=>{const f=await fixture();try{await f.host.tick();assert.equal(f.host.enabled,false);await f.host.consent(true);assert.equal(f.host.enabled,true);f.states[1].connected=false;await f.host.tick();assert.equal(f.host.enabled,false);assert.equal(f.routes.at(-1),false);}finally{await f.done();}});
test('stranger disconnect closes that browser and disables routing',async()=>{const f=await fixture();try{await f.host.consent(true);f.states[0].ended=true;await f.host.tick();assert.equal(f.host.slots[0],null);assert.ok(f.host.slots[1]);assert.equal(f.host.requested,false);assert.equal(f.host.enabled,false);assert.equal(f.routes.at(-1),false);}finally{await f.done();}});
test('old capture chunks cannot leak into a replacement audio session',async()=>{const f=await fixture();const r=new EventEmitter();const writes=[];r.writeHead=()=>{};r.write=s=>writes.push(s);r.end=()=>r.emit('close');try{f.host.subscribe(0,r);const child=f.host.captures[0];child.stdout.emit('data',Buffer.alloc(2048));assert.equal(writes.filter(s=>s.startsWith('data:')).length,1);f.host.slots[0]={...f.host.slots[0],epoch:'new'};child.stdout.emit('data',Buffer.alloc(2048));assert.equal(writes.filter(s=>s.startsWith('data:')).length,1);}finally{await f.done();}});
test('meters measure each side independently without a listening subscriber',async()=>{const f=await fixture();try{await f.host.tick();const tone=Buffer.alloc(2048);for(let n=0;n<1024;n++)tone.writeInt16LE(8192,n*2);f.host.captures[0].stdout.emit('data',tone);f.host.captures[1].stdout.emit('data',Buffer.alloc(2048));const status=f.host.status();assert.equal(status.slots[0].db,-12);assert.equal(status.slots[0].level,80);assert.equal(status.slots[1].level,0);const old=f.host.captures[0];f.states[0].connected=false;await f.host.tick();assert.equal(f.host.captures[0],null);assert.equal(f.host.status().slots[0].level,0);old.stdout.emit('data',tone);assert.equal(f.host.status().slots[0].level,0);}finally{await f.done();}});
function voiceFixture({authenticated=false,live='expected-token',saved=live,restricted=false}={}){const old={document:global.document,localStorage:global.localStorage};let listener=()=>{},writes=0,requests=0;const user={authToken:live,tokenId:authenticated?321:null},system={isAuth:authenticated,socketConnected:true,forceDisconnectReason:restricted?'fixture-restriction':null};const store={state:{user,system},subscribe:fn=>{listener=fn;return()=>{listener=()=>{};};},commit:()=>writes++};global.document={querySelectorAll:()=>[{__vue__:{$store:store,$socketActions:{authorize:()=>requests++}}}]};global.localStorage={getItem:()=>JSON.stringify({user:{authToken:saved}}),setItem:()=>writes++};return {store,user,system,emit:()=>listener({type:'native-update'}),counts:()=>({writes,requests}),done:()=>{global.document=old.document;global.localStorage=old.localStorage;}};}
test('voice confirms existing native authorization without writing storage or sending a request',async()=>{const f=voiceFixture({authenticated:true});try{const result=await confirmVoiceSession({token:'expected-token',timeout:100});assert.equal(result.ok,true);assert.equal(result.reason,'native-session-confirmed');assert.deepEqual(f.counts(),{writes:0,requests:0});}finally{f.done();}});
test('voice waits for native startup to finish without manual authorization',async()=>{const f=voiceFixture();try{const pending=confirmVoiceSession({token:'expected-token',timeout:200});await new Promise(r=>setTimeout(r,10));assert.deepEqual(f.counts(),{writes:0,requests:0});f.user.tokenId=321;f.system.isAuth=true;f.emit();const result=await pending;assert.equal(result.ok,true);assert.deepEqual(f.counts(),{writes:0,requests:0});}finally{f.done();}});
test('voice stops when native startup requires verification, rejects the token or reports a restriction',async()=>{for(const kind of ['verification','token','restriction']){const f=voiceFixture(kind==='token'?{authenticated:true,live:'different-token'}:kind==='restriction'?{restricted:true}:{});try{const pending=confirmVoiceSession({token:'expected-token',timeout:200});if(kind==='verification'){f.system.captchaRequired=true;f.emit();}const result=await pending;assert.equal(result.ok,false);assert.equal(result.reason,kind==='verification'?'verification-required':kind==='token'?'token-not-accepted':'native-restriction');assert.deepEqual(f.counts(),{writes:0,requests:0});}finally{f.done();}}});
test('voice startup timeout never retries authorization',async()=>{const f=voiceFixture();try{const result=await confirmVoiceSession({token:'expected-token',timeout:20});assert.equal(result.reason,'native-authorization-timeout');assert.deepEqual(f.counts(),{writes:0,requests:0});}finally{f.done();}});
test('native registration rejection is reported without requesting a replacement token',async()=>{const f=voiceFixture();try{f.system.errorRegistered=425;const result=await confirmVoiceSession({token:'expected-token',timeout:100});assert.equal(result.reason,'native-registration-error-425');assert.equal(result.diagnostics.registrationError,425);assert.deepEqual(f.counts(),{writes:0,requests:0});}finally{f.done();}});
test('polling preserves a failed startup reason and never repeats preparation automatically',async()=>{const f=await fixture();let preparations=0;try{f.states[0]={status:'ready',connected:false};f.host.slots[0].connected=false;f.host.prepare=async()=>{preparations++;throw Error('Nekto rejected voice registration (code 425).');};await assert.rejects(f.host.start(0),/425/);await f.host.tick();await f.host.tick();const status=f.host.status().slots[0];assert.equal(status.status,'error');assert.match(status.error,/425/);assert.equal(preparations,1);}finally{await f.done();}});
