'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');const {installedPaths,resolveBrowser}=require('../src/browser-choice.cjs');
const env={PROGRAMFILES:'C:\\Program Files',LOCALAPPDATA:'C:\\Users\\fixture\\AppData\\Local'},files=installedPaths('win32',env);
function options(present){return {platform:'win32',bundledPath:'C:\\cache\\chromium.exe',exists:file=>present.includes(file)};}
test('Windows auto chooses installed per-user Chrome and skips missing bundled binary',()=>{const file=files.chrome[1];assert.deepEqual(resolveBrowser(env,options([file])),{label:'Google Chrome',launch:{executablePath:file}});});
test('Windows auto falls back to Edge; the selected executable is used directly',()=>{const file=files.msedge[0];assert.equal(resolveBrowser(env,options([file])).launch.executablePath,file);});
test('existing bundled Chromium uses regular browser channel without a headless-shell download',()=>{assert.deepEqual(resolveBrowser(env,options(['C:\\cache\\chromium.exe'])).launch,{channel:'chromium'});assert.equal(resolveBrowser(env,options([])),null);});
test('explicit channel never silently switches browsers and bad options are actionable',()=>{assert.throws(()=>resolveBrowser({...env,BROWSER_CHANNEL:'chrome'},options([files.msedge[0]])),/Selected browser chrome is not installed/);assert.throws(()=>resolveBrowser({...env,BROWSER_CHANNEL:'unknown'},options([])),/BROWSER_CHANNEL/);assert.equal(resolveBrowser({...env,BROWSER_CHANNEL:'msedge'},options([files.chrome[0],files.msedge[0]])).label,'Microsoft Edge');});
test('custom executable overrides auto selection, but missing paths fail before downloads',()=>{assert.deepEqual(resolveBrowser({...env,CHROMIUM_EXECUTABLE:'D:\\Portable Chrome\\chrome.exe'},options(['D:\\Portable Chrome\\chrome.exe'])).launch,{executablePath:'D:\\Portable Chrome\\chrome.exe'});assert.throws(()=>resolveBrowser({...env,CHROMIUM_EXECUTABLE:'missing'},options([])),/CHROMIUM_EXECUTABLE/);});
