import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {parseHTML} from 'linkedom';import {Relay} from '../relay.js';
const source=await readFile(new URL('../browser/adapter.js',import.meta.url),'utf8')+'\n'+await readFile(new URL('../browser/runtime.js',import.meta.url),'utf8');
function fixture(){
 const {window,document}=parseHTML('<html><body><section id="conversation"></section><div class="emojionearea-editor" contenteditable="true" aria-disabled="true"></div><button id="sendMessageBtn">Отправить</button></body></html>');
 window.HTMLElement.prototype.getClientRects=function(){return this.isConnected&&this.style.display!=='none'?[{}]:[];};
 const ctx={window:{},document,crypto:{randomUUID:()=>Math.random().toString(36)},location:{hash:'#/conversation'},CSS:{escape:s=>s},Event:window.Event,KeyboardEvent:window.Event,HTMLInputElement:window.HTMLInputElement,HTMLTextAreaElement:window.HTMLTextAreaElement,WeakMap,WeakSet,setTimeout};vm.createContext(ctx);vm.runInContext(source,ctx);
 const editor=document.querySelector('.emojionearea-editor'),sent=[];
 document.getElementById('sendMessageBtn').addEventListener('click',()=>{sent.push(editor.textContent);const bubble=document.createElement('div');bubble.className='mess_block self';const text=document.createElement('div');text.className='window_chat_dialog_text';text.textContent=editor.textContent;bubble.append(text);document.getElementById('conversation').append(bubble);editor.textContent='';});
 return {host:ctx.window.__textHost,sent,button:document.getElementById('sendMessageBtn'),connect(){editor.setAttribute('aria-disabled','false');},incoming(value){const bubble=document.createElement('div');bubble.className='mess_block';const text=document.createElement('div');text.className='window_chat_dialog_text';text.textContent=value;bubble.append(text);document.getElementById('conversation').append(bubble);return text;},editor};
}
test('first message at connection is forwarded and outgoing bubbles never loop',async()=>{const a=fixture(),b=fixture(),relay=new Relay();relay.toggle(true);relay.update(0,a.host.poll());relay.update(1,b.host.poll());a.connect();b.connect();a.incoming('first message');const sa=a.host.poll(),sb=b.host.poll();assert.equal(sa.messages.length,1);relay.update(0,sa);relay.update(1,sb);relay.incoming(0,sa.messages[0].text);const delivery=relay.members[1].queue.shift();assert.equal(await b.host.send(delivery.text,delivery.targetEpoch),'submitted');assert.deepEqual(b.sent,['first message']);assert.equal(b.host.poll().messages.length,0);b.incoming('reply');const reply=b.host.poll();relay.incoming(1,reply.messages[0].text);const back=relay.members[0].queue.shift();assert.equal(await a.host.send(back.text,back.targetEpoch),'submitted');assert.deepEqual(a.sent,['reply']);assert.equal(a.host.poll().messages.length,0);});
test('private operator message stays on its selected side',async()=>{const a=fixture(),b=fixture(),relay=new Relay();relay.toggle(true);a.host.poll();b.host.poll();a.connect();b.connect();relay.update(0,a.host.poll());relay.update(1,b.host.poll());relay.enqueue(0,{text:'private message',kind:'private'});assert.equal(relay.members[1].queue.length,0);const item=relay.members[0].queue.shift();assert.equal(await a.host.send(item.text,item.targetEpoch),'submitted');assert.deepEqual(a.sent,['private message']);assert.equal(a.host.poll().messages.length,0);assert.deepEqual(b.sent,[]);});
test('drafts are preserved and stale conversations are rejected',async()=>{const a=fixture();a.host.poll();a.connect();const s=a.host.poll();a.editor.textContent='draft';assert.equal(await a.host.send('relay',s.epoch),'draft');assert.equal(a.editor.textContent,'draft');a.editor.textContent='';a.editor.setAttribute('aria-disabled','true');a.host.poll();a.connect();a.host.poll();assert.equal(await a.host.send('old',s.epoch),'changed');assert.deepEqual(a.sent,[]);});

test('disabled empty Send button is enabled by editor synchronization before sending',async()=>{const a=fixture();a.host.poll();a.connect();const state=a.host.poll();a.button.disabled=true;a.editor.addEventListener('keyup',()=>setTimeout(()=>a.button.disabled=false,120));assert.equal(await a.host.send('message',state.epoch),'submitted');assert.deepEqual(a.sent,['message']);});
