'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {Mixer,LivePCM,encodeStereo,decodeStereo,FRAME}=require('../src/audio.cjs'),Codec=require('opusscript');const {installBridge}=require('../browser/guest-bridge'),{installPCMRuntime}=require('../browser/audio-runtime'),{pcmWorkletSource}=require('../browser/pcm-worklet');
(async()=>{let browser,server,pump,boardPump,raw,player;try{server=http.createServer((_req,res)=>res.end('<!doctype html><html><body></body></html>')).listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});const mixer=new Mixer();mixer.enabled=true;mixer.activate(0,true);mixer.activate(1,true);const pages=[];
 for(let slot=0;slot<2;slot++){const page=await browser.newPage();await page.exposeFunction('captureRemote',samples=>mixer.pushRemote(slot,samples));await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(()=>{window.__neonAudio={send:samples=>{captureRemote(samples).catch(()=>{});},receive:fn=>window.acceptMix=fn,state:()=>{}};});if(process.env.FORCE_FALLBACK)await page.evaluate(()=>{Object.defineProperty(AudioContext.prototype,'audioWorklet',{get:()=>({addModule:async()=>{throw new DOMException('fixture module failure','AbortError');}})});});await page.evaluate(`(${installPCMRuntime.toString()})(${JSON.stringify(pcmWorkletSource())});(${installBridge.toString()})({bridgeAudio:false},${JSON.stringify(pcmWorkletSource())})`);await page.evaluate(async hz=>{window.ctx=new AudioContext({sampleRate:48000});const tone=ctx.createOscillator(),gain=ctx.createGain(),dst=ctx.createMediaStreamDestination(),audio=document.createElement('audio');gain.gain.value=.12;tone.frequency.value=hz;tone.connect(gain).connect(dst);tone.start();audio.srcObject=dst.stream;document.body.append(audio);const silent=ctx.createGain(),dummy=ctx.createOscillator(),startup=ctx.createMediaStreamDestination();dummy.connect(silent);silent.gain.value=0;silent.connect(startup);dummy.start();window.pc=new RTCPeerConnection();window.sender=pc.addTrack(startup.stream.getAudioTracks()[0],startup.stream);Object.defineProperty(pc,'connectionState',{value:'connected',configurable:true});await ctx.resume();await __neonBridge.attachSenders([pc]);window.meter=ctx.createAnalyser();meter.fftSize=8192;meter.smoothingTimeConstant=0;const zero=ctx.createGain();zero.gain.value=0;ctx.createMediaStreamSource(new MediaStream([sender.track])).connect(meter);meter.connect(zero);zero.connect(ctx.destination);},[540,900][slot]);pages.push(page);}
 let cursor=0;const codec=new Codec(48000,2,Codec.Application.VOIP);boardPump=setInterval(()=>{const samples=Float32Array.from({length:FRAME},()=>.1*Math.sin(2*Math.PI*1400*cursor++/48000));mixer.pushUser('human',codec.decode(codec.encode(encodeStereo(samples),FRAME)));},20);
 let busy=false,encodedFrames=0;const discordCodec=new Codec(48000,2,Codec.Application.VOIP);
 const {createAudioPlayer,createAudioResource,StreamType,NoSubscriberBehavior}=require('@discordjs/voice');
 raw=new LivePCM(mixer,frames=>{encodedFrames++;if(busy)return;busy=true;Promise.all(pages.map((p,i)=>p.evaluate(samples=>acceptMix(samples),Array.from(frames[i])))).catch(()=>{}).finally(()=>busy=false);});
 player=createAudioPlayer({behaviors:{noSubscriber:NoSubscriberBehavior.Play}});player.play(createAudioResource(raw,{inputType:StreamType.Raw}));
 await new Promise(r=>setTimeout(r,1700));const spectra=await Promise.all(pages.map(p=>p.evaluate(()=>{const bins=new Float32Array(meter.frequencyBinCount);meter.getFloatFrequencyData(bins);return [540,900,1400].map(hz=>{const center=Math.round(hz*8192/48000);return Math.max(...bins.slice(center-2,center+3));});})));assert.ok(spectra[0][0]<-65&&spectra[0][1]>-45&&spectra[0][2]>-45,JSON.stringify(spectra));assert.ok(spectra[1][1]<-65&&spectra[1][0]>-45&&spectra[1][2]>-45,JSON.stringify(spectra));assert.ok(encodedFrames>30);console.log(JSON.stringify({pass:true,mode:process.env.FORCE_FALLBACK?'compatible':'worklet',spectra,opusFrames:encodedFrames,RTP:'connection state simulated; no live Discord/Nekto calls'}));
 codec.delete();discordCodec.delete();
 }catch(error){console.error(error);process.exitCode=1;}finally{clearInterval(pump);clearInterval(boardPump);player?.stop(true);raw?.destroy();await browser?.close();server?.close();}})();
