'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {installSearchController}=require('../browser/search-controller');
const {BrowserLink}=require('../src/browser-link.cjs');
function fixture(){let state='search-ready',clicks=0;const world={window:{}};vm.runInNewContext('('+installSearchController.toString()+')(inspect)',{...world,inspect:options=>{if(options?.click)clicks++;return {status:state,message:state};}});return {api:world.window.__neonSearch,set:s=>state=s,get clicks(){return clicks;}};}
test('manual and automatic search share one pending request until a call ends',()=>{const f=fixture();f.api.request('manual');f.api.request('automatic');f.api.request('manual');assert.equal(f.clicks,1);f.set('searching');f.api.observe();f.set('search-ready');f.api.request();assert.equal(f.clicks,1);f.set('in-call');f.api.observe();f.set('search-ready');f.api.request();assert.equal(f.clicks,2);});
test('refusal after click is retained and prevents all further clicks',()=>{const f=fixture();f.api.request();f.set('blocked');assert.equal(f.api.request('automatic').status,'blocked');assert.equal(f.api.request('manual').status,'blocked');assert.equal(f.clicks,1);});
test('setup, challenge and temporary errors never trigger a search',()=>{for(const status of ['setup','verification','temporary-error','loading']){const f=fixture();f.set(status);assert.equal(f.api.request().status,status);assert.equal(f.clicks,0);}});
test('concurrent opens create one caller session and closing waits for initialization',async()=>{const b=new BrowserLink({activate(){}},{});let created=0,closed=0,release;const gate=new Promise(r=>release=r);b.openSlot=async slot=>{created++;const e={};b.slots[slot]=e;await gate;return e;};b.closeSlot=async slot=>{closed++;b.slots[slot]=null;};const first=b.open(0),second=b.open(0);assert.equal(created,1);const close=b.close(0);assert.equal(closed,0);release();assert.equal(await first,await second);await close;assert.equal(closed,1);assert.equal(b.slots[0],null);});
test('initialization failure releases the opening lock for an explicit later open',async()=>{const b=new BrowserLink({activate(){}},{});let attempts=0;b.openSlot=async()=>{attempts++;throw Error('fixture failure');};await assert.rejects(b.open(0));await assert.rejects(b.open(0));assert.equal(attempts,2);});
