import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import {Relay} from '../relay.js';import {Transcript} from '../transcript.js';import {closeSession} from '../session-lifecycle.js';
const source=await readFile(new URL('../server.js',import.meta.url),'utf8');
const closeSource=source.slice(source.indexOf('async function closeSlot('),source.indexOf('async function authorize('));
const tickSource=source.slice(source.indexOf('async function tick(i)'),source.indexOf('setInterval(()=>'));
function fixture(state,{saveFails=false}={}){const events=[],relay=new Relay(),transcripts=[new Transcript(),new Transcript()],locks=[null,null],tokenStatus=[true,true];relay.toggle(true);for(let i=0;i<2;i++){relay.update(i,{connected:true,epoch:'epoch'+i});transcripts[i].reset('epoch'+i);transcripts[i].add('incoming','original');}
 const slots=[0,1].map(i=>({page:{url:()=> 'https://nekto-me.kz/chat/',evaluate:async()=>state},context:{async storageState(){events.push('save'+i);if(saveFails)throw Error('disk failure');},async close(){events.push('close'+i);}},busy:false,opening:false,status:'connected',saveAt:Date.now()}));
 relay.incoming(1,'queued to A');relay.incoming(0,'queued to B');
 const sandbox={URL,slots,relay,transcripts,locks,tokenStatus,closeSession,data:'/fixture',labels:['A','B'],console:{log(){}},operationError(i,error){throw error;},setTimeout};vm.createContext(sandbox);vm.runInContext(closeSource+tickSource+';globalThis.runTick=tick;',sandbox);
 return {slots,relay,transcripts,locks,tokenStatus,events,tick:sandbox.runTick};}
test('ended stranger closes only that session and invalidates queued deliveries',async()=>{const f=fixture({connected:false,status:'ended',ended:true,epoch:'closed',messages:[]});await f.tick(0);assert.equal(f.slots[0],null);assert.ok(f.slots[1]);assert.deepEqual(f.events,['save0','close0']);assert.equal(f.relay.members[0].queue.length,0);assert.equal(f.relay.valid(1,f.relay.members[1].queue[0]),false);assert.equal(f.transcripts[0].items.length,0);assert.equal(f.transcripts[1].items.length,1);assert.equal(f.tokenStatus[0],false);assert.equal(f.locks[0],null);});
test('searching and verification states do not automatically close browsers',async()=>{for(const status of ['searching','verification','loading']){const f=fixture({connected:false,status,ended:false,epoch:'changed',messages:[]});await f.tick(0);assert.ok(f.slots[0]);assert.deepEqual(f.events,[]);}});
test('session still closes if saving its browser storage fails',async()=>{const f=fixture({connected:false,status:'ended',ended:true,epoch:'closed',messages:[]},{saveFails:true});await f.tick(0);assert.equal(f.slots[0],null);assert.deepEqual(f.events,['save0','close0']);});
test('stale cleanup cannot close a replacement session',async()=>{const f=fixture({});const previous=f.slots[0];f.slots[0]={context:{close(){throw Error('replacement must stay open');}}};assert.equal(await closeSession({slots:f.slots,index:0,expected:previous,relay:f.relay,transcript:f.transcripts[0],tokenStatus:f.tokenStatus,path:'/fixture'}),false);assert.ok(f.slots[0]);assert.deepEqual(f.events,[]);});
